#!/bin/bash
## Pruebas de rendimiento sobre sistemas de archivos EXT3

# creamos archivo en bruto que representara una partición virtual
# crearemos una particion apartir de un archivo a manera de estudio
# pero tambien puede aplicacar sobre particiones nativas
# creamos con el mandato dd una particion con datos nulos de 100000 bloques (1 bloque = 512 Bytes)
echo "El script esta creando el archivo"
dd if=/dev/zero of=ext3.fs count=8194304
# formatear el archivo creado
time mkfs.ext3 ext3.fs
#crear carpeta de montaje
mkdir /test/particion_ext3
# Mapear el archivo a loop, ext3.fs queda referenciado por /dev/loop0
losetup /dev/loop1 ext3.fs
# montamos el archivo al directorio creado con anterioridad
mount -t ext3 /dev/loop1 /test/particion_ext3
