#!/bin/bash
#Buscar dentro del directorio /var/log los archivos que hayan sido modificados entre ayer y anteayer.

echo "Eston son los archivos que se modificaron entre ayer y anteayer en  el directorio /var/log"
echo "PD: algunos archivos necesiton privilegios para verlos, para esto debera loguearse como usuario root"
ayer=`find /var/log -mtime 1`
echo "$ayer"
