#!/bin/bash


echo "Los puntos de montaje de almacenamiento son:"
echo ""
mont5=`mount | grep /dev/sda | awk '{print $1,$2,$3,$4,$5}'  `
mont1=`mount | grep /media | awk '{print $1,$2,$3,$4,$5}' `
mont4=`mount | grep /dev/sr  | awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9}'`

echo "$mont5"
echo "$mont1"
echo "$mont4"
