#!/bin/bash
## Pruebas de rendimiento sobre sistemas de archivos reiserfs

# creamos archivo en bruto que representara una partición virtual
# crearemos una particion apartir de un archivo a manera de estudio
# pero tambien puede aplicacar sobre particiones nativas
# creamos con el mandato dd una particion con datos nulos de 100000 bloques (1 bloque = 512 Bytes)
echo "El scritp esta creando el archivo"
dd if=/dev/zero of=reiserfs.fs count=8194304
# formatear el archivo creado
time mkfs.reiserfs reiserfs.fs
#crear carpeta de montaje
mkdir /test/particion_reiserfs
# Mapear el archivo a loop, reiserfs.fs queda referenciado por /dev/loop7
losetup /dev/loop5 reiserfs.fs
# montamos el archivo al directorio creado con anterioridad
mount -ft reiserfs /dev/loop5 /test/particion_reiserfs

